// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2KxFFyhgggrCwMZlofiNT4vJ7abx_yMw',
    appId: '1:945431553299:web:53c0ec78c98277892c26e6',
    messagingSenderId: '945431553299',
    projectId: 'desafio-digiup',
    authDomain: 'desafio-digiup.firebaseapp.com',
    storageBucket: 'desafio-digiup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsAIDKndE2L8p5by5Sdn1K15rDwpDqfI',
    appId: '1:945431553299:android:fd0c550ff38d51c42c26e6',
    messagingSenderId: '945431553299',
    projectId: 'desafio-digiup',
    storageBucket: 'desafio-digiup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMWRP6UR3MYjC0X8VHHF7PnG3Ovsa4V6Q',
    appId: '1:945431553299:ios:213fe83ddc7710932c26e6',
    messagingSenderId: '945431553299',
    projectId: 'desafio-digiup',
    storageBucket: 'desafio-digiup.appspot.com',
    iosBundleId: 'com.digiup.miguel.desafio3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMWRP6UR3MYjC0X8VHHF7PnG3Ovsa4V6Q',
    appId: '1:945431553299:ios:213fe83ddc7710932c26e6',
    messagingSenderId: '945431553299',
    projectId: 'desafio-digiup',
    storageBucket: 'desafio-digiup.appspot.com',
    iosBundleId: 'com.digiup.miguel.desafio3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2KxFFyhgggrCwMZlofiNT4vJ7abx_yMw',
    appId: '1:945431553299:web:047b38dfe1a4aa932c26e6',
    messagingSenderId: '945431553299',
    projectId: 'desafio-digiup',
    authDomain: 'desafio-digiup.firebaseapp.com',
    storageBucket: 'desafio-digiup.appspot.com',
  );
}
